Dev-12_BU_Wordsearch
The-Escape-Squad/DC2060-Team-Project pull request #5
Opened 2021-04-26 14:37 UTC by beccamupton

2021-04-27 12:19 UTC, cubastanley requested changes
Just some cosmetic change requests - really solid though, I think I'll need a hand from you with integrating this with the game levels definitely 😂 may need to refactor a couple of bits for that but we'll cross that bridge when we get to it

2021-04-27 12:19 UTC, cubastanley commented on Assets/Scripts/SearchingWord.cs
> +using System.Collections;
Think you can delete this script?

2021-04-27 12:19 UTC, cubastanley commented on Assets/Scripts/SearchingWordsList.cs
> +using System.Collections;
Should probably delete this script

2021-04-27 12:20 UTC, cubastanley commented on Assets/Scripts/WordsGrid.cs
> +    private float GetHelfScreenWidth()
Im assuming this one is a typo?

2021-04-27 13:04 UTC, beccamupton commented on Assets/Scripts/WordsGrid.cs
> +    private float GetHelfScreenWidth()
haha yes

2021-04-29 11:56 UTC, cubastanley approved these changes

2021-04-29 12:50 UTC, merged